### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'on')

### ISSUE THREAD

**Issue by Nowaker** [locize/locizify-ssg#2]
## 🐛 Bug Report

```
% PUBLIC_DIR=_gatsby/public node ./_translate-pages-new.mjs
file:///home/nowaker/projekty/dreamhost/dreamhost-com/node_modules/locizify-ssg/dist/esm/index.js:26
    locizify.i18next.on('initialized', resolve);
                     ^

TypeError: Cannot read properties of undefined (reading 'on')
    at file:///home/nowaker/projekty/dreamhost/dreamhost-com/node_modules/locizify-ssg/dist/esm/index.js:26:22
    at new Promise (<anonymous>)
    at ssgLng (file:///home/nowaker/projekty/dreamhost/dreamhost-com/node_modules/locizify-ssg/dist/esm/index.js:25:16)
    at async file:///home/nowaker/projekty/dreamhost/dreamhost-com/_translate-pages-new.mjs:7:1
```

## To Reproduce

```
# _translate-pages-new.mjs
import ssg from 'locizify-ssg'

const dir = process.env.PUBLIC_DIR || '_site/'

const file = `${dir}/es/index.html`

await ssg(file, 'es', file, {
  backend: {
    projectId: '3f516219-6546-4f2a-9030-fc31659dc115',
    apiKey: 'xxx',
    referenceLng: 'en'
  },
  fallbackLng: 'en',
  saveMissing: false,
  debug: false,
  namespace: 'root',
  ns: ['common'],
  translateAttributes: ['placeholder', 'title', 'alt', 'content#meta.name=description', 'content#meta.name=keywords', 'content#meta.property', 'value#input.type=submit', 'value#input.type=button', 'value#input.type=reset'],
  ignoreTags: ['script', 'style', 'iframe', 'svg'],
});
```
## Expected behavior

No error.

## Your Environment

- *runtime version*: 16
- *module version*: latest
- *os*: Linux

**Comment by adrai** [comment]
How does your html look like?
how is locizify initialized (not locizify-ssg)?
is it lazy initialized?
a reproducible example repo including all relevant files etc... may help...

**Comment by Nowaker** [comment]
> How does your html look like?

https://github.com/locize/locizify-ssg/files/8789656/index.tar.gz

> how is locizify initialized (not locizify-ssg)?

Not initialized, not embedded, at all. I simply ran `locizify-ssg` against a static file that does not have any `<script>` to Locizify.

**Comment by adrai** [comment]
i think we can close this in favor of #1

**Comment by adrai** [comment]
v1.0.3 should be better
